import uuid

from django.conf import settings
from django.db import models


class Device(models.Model):
    """A device that produces monitoring sessions.

    The primary key is a UUID rather than an auto-increment integer because
    FastAPI will later store device ids as plain UUID values in its own
    database, with no foreign key back to Django. A UUID can be generated by
    Django, so both sides agree on the identifier without a lookup.
    """

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        DISABLED = "disabled", "Disabled"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="devices",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name
